### PR TITLE
fix: add directory watchers to update the cache

### LINKED ISSUE #261: Newly added files are not offered in autocomplete
<details>
<summary>Prerequisites</summary>

### Prerequisites

- [ X] Put an X between the brackets on this line if you have done all of the following:
  - Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
  - Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
  - Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
  - Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
  - Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

</details>

### Description

I updated the package and now it no longer works.  If I create a file (any kind, .js, .scss, .css etc) autocomplete will not find it until I restart Atom. Once I restart it'll work for all current files but again, if I add a new file it will not autocomplete that file until I restart Atom.  Having to restart Atom every single time I create a component in React just for auto complete is a bit annoying.

### Steps to Reproduce

1. Create a file
2. Try to import that file in another location

**Expected behavior:** The path autocompletes as I type
**Actual behavior:** nothing happens unless I restart Atom.

**Reproduces how often:** 100%

### Versions

Atom: 
Atom    : 1.55.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

OS:
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

### Additional Information

It was working fine until I updated.  The update had been sitting there for a few days and I just updated it today.

### PR DESCRIPTION
**Pull request by aminya**
Uses chokidar to track file/folder changes. Atom's built-in watcher is not recursive which makes it hard to work with.
Related to https://github.com/atom/node-pathwatcher/issues/135

Fixes #261

### CODE REVIEW

File: lib/paths-cache.js [hunk 1]
```diff
@@ -140,20 +141,48 @@ export default class PathsCache extends EventEmitter {
...
+    )
+    return result
+  }
+
+  /**
+   * Add a watcher for the projectDirectory
+   * @param  {Directory} projectDirectory
+   * @private
+   */
+  async _addWatcherForDirectory(projectDirectory) {
```
Comment (aminya) [inline lib/paths-cache.js:161]: I'm not sure why, but Atom's path watcher doesn't seem to work

Comment (aminya) [reply lib/paths-cache.js:161]: I tested on Atom stable

Comment (aminya) [reply lib/paths-cache.js:168]: Might be related to https://github.com/atom-community/autocomplete-paths/pull/262

Comment (aminya) [reply lib/paths-cache.js:168]: Also, it seems that `directory.onDidChange` is not recursive!

https://github.com/atom/node-pathwatcher#pathwatcherwatchfilename-listener

Comment (aminya) [reply lib/paths-cache.js:168]: We should switch to Chokidar:
https://www.npmjs.com/package/chokidar
