### PR TITLE
Fix leftover interval timer

### LINKED ISSUE #183: Uncaught TypeError: Cannot read property 'fileCount' of null
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package 2.12.1

### Stack Trace

Uncaught TypeError: Cannot read property 'fileCount' of null

```
At /home/sreejith/.atom/packages/autocomplete-paths/lib/autocomplete-paths.js:87

TypeError: Cannot read property 'fileCount' of null
    at /packages/autocomplete-paths/lib/autocomplete-paths.js:87:39
```

### Commands

```
     -0:43 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
aligner-php 1.2.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-clock 0.1.15 
atom-ide-ui 0.5.2 
atom-minify 0.8.0 
atomic-chrome 0.3.2 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-modules 1.7.3 
autocomplete-paths 2.12.1 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
emmet 2.4.3 
file-icons 2.1.13 
highlight-line 0.12.0 
highlight-selected 0.13.1 
Hydrogen 2.0.1 
hyperclick 0.1.5 
ide-php 0.6.9 
ide-typescript 0.6.2 
intentions 1.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
linter 2.2.0 
linter-jscs 4.1.3 
linter-jshint 3.1.6 
linter-jsonlint 1.3.0 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-stylelint 4.0.2 
linter-ui-default 1.6.10 
minimap 4.29.7 
nucleus-dark-ui 0.12.3 
php-cs-fixer 4.1.1 
php-debug 0.2.5 
php-hyperclick 1.2.1 
php-integrator-autocomplete-plus 1.6.0 
pigments 0.40.2 
svn 0.0.13 
sync-settings 0.8.3 
text-pastry 0.6.1 
wordpress-api 1.2.2 
```

### PR DESCRIPTION
**Pull request by avaly**
Closes #183

### CODE REVIEW

File: lib/autocomplete-paths.js [hunk 1]
```diff
@@ -45,6 +45,9 @@ export default {
   },
 
   deactivate: function () {
+    if (this._statusBarInterval) {
+      clearInterval(this._statusBarInterval)
+    }
```
Comment (aminya) [inline lib/autocomplete-paths.js:50]:
```suggestion
    if (this._statusBarInterval) {
      clearInterval(this._statusBarInterval);
    }
```

File: lib/autocomplete-paths.js [hunk 2]
```diff
@@ -90,16 +93,23 @@ export default {
...
   },
 
   /**
    * Hides the status bar tile
    */
   _hideStatusBarTile () {
-    clearInterval(this._statusBarInterval)
+    if (this._statusBarInterval) {
+      clearInterval(this._statusBarInterval)
+    }
```
Comment (aminya) [inline lib/autocomplete-paths.js:112]:
```suggestion
    if (this._statusBarInterval) {
      clearInterval(this._statusBarInterval);
    }
```

File: lib/autocomplete-paths.js [hunk 3]
```diff
@@ -90,16 +93,23 @@ export default {
...
     this._statusBarInterval = setInterval(() => {
-      const fileCount = this._provider.fileCount;
-      this._statusBarElement.innerHTML = `Rebuilding paths cache... ${fileCount} files`;
+      if (!this._provider) {
+        return
+      }
+      const fileCount = this._provider.fileCount
+      if (fileCount > 0) {
+        this._statusBarElement.innerHTML = `Rebuilding paths cache... ${fileCount} files`
+      }
```
Comment (aminya) [inline lib/autocomplete-paths.js:102]: I added a provider check in #233 
```suggestion
      const fileCount = this._provider.fileCount;
      if (fileCount > 0) {
        this._statusBarElement.innerHTML = `Rebuilding paths cache... ${fileCount} files`;
      }
```
